In [1]:
# load packages and data
import pandas as pd
from math import log
data = pd.read_csv('testwords.csv')
data

,user,cat,dog,economics,green,narwhal,happy,bacon,bumpy,crazy,holy,keys
0,1,1,0,1,0,0,1,0,1,0,0,0
1,33,0,0,0,1,0,0,0,0,0,0,0
2,42,0,0,0,0,0,1,0,0,0,0,0
3,51,0,0,0,0,0,0,0,0,0,1,0
4,62,0,1,0,1,1,0,0,0,0,0,0
5,75,0,0,0,0,1,0,0,0,1,1,0
6,130,0,0,0,0,0,0,0,0,0,0,0
7,141,0,0,0,0,0,0,0,0,1,1,1
8,144,0,1,1,0,0,0,1,0,0,0,0
9,150,0,0,1,0,0,0,0,0,0,0,0
10,205,0,0,1,0,0,0,1,0,0,1,0
11,247,0,0,0,1,0,0,1,0,0,0,0
12,256,1,0,0,1,0,0,0,0,1,1,0
13,299,0,0,0,0,0,0,0,0,0,0,1
14,313,1,0,0,0,0,0,0,0,0,0,0
15,319,0,0,0,0,0,1,0,0,1,0,0
16,336,1,0,1,0,0,1,0,1,0,0,0
17,367,0,0,0,0,1,0,0,0,0,0,0
18,371,1,0,0,0,1,0,0,0,1,0,0
19,383,1,1,0,0,0,0,0,0,1,1,0
20,422,0,0,0,0,0,0,0,0,0,1,0
21,428,0,0,1,0,1,1,0,0,0,0,0

In [2]:
# take out the user id column
dataNoUser = data.drop('user',1)
dataNoUser

,cat,dog,economics,green,narwhal,happy,bacon,bumpy,crazy,holy,keys
0,1,0,1,0,0,1,0,1,0,0,0
1,0,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,0
4,0,1,0,1,1,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,1,1,0
6,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,1,1,1
8,0,1,1,0,0,0,1,0,0,0,0
9,0,0,1,0,0,0,0,0,0,0,0
10,0,0,1,0,0,0,1,0,0,1,0
11,0,0,0,1,0,0,1,0,0,0,0
12,1,0,0,1,0,0,0,0,1,1,0
13,0,0,0,0,0,0,0,0,0,0,1
14,1,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,1,0,0,1,0,0
16,1,0,1,0,0,1,0,1,0,0,0
17,0,0,0,0,1,0,0,0,0,0,0
18,1,0,0,0,1,0,0,0,1,0,0
19,1,1,0,0,0,0,0,0,1,1,0
20,0,0,0,0,0,0,0,0,0,1,0
21,0,0,1,0,1,1,0,0,0,0,0

In [3]:
# make an empty matrix of column names
crossmat = pd.DataFrame(index=dataNoUser.columns, columns=dataNoUser.columns)
crossmat

           cat  dog economics green narwhal happy bacon bumpy crazy holy keys
cat        NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
dog        NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
economics  NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
green      NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
narwhal    NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
happy      NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
bacon      NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
bumpy      NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
crazy      NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
holy       NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN
keys       NaN  NaN       NaN   NaN     NaN   NaN   NaN   NaN   NaN  NaN  NaN

In [4]:
sing_probs = dict() #establish empty dictionary for singular probabilities
indexLen = len(dataNoUser.index) #number of rows

for x in dataNoUser:
    sing_probs[x] = sum(dataNoUser[x])/float(indexLen)
print sing_probs

{'crazy': 0.27272727272727271, 'holy': 0.31818181818181818, 'keys': 0.090909090909090912, 'economics': 0.27272727272727271, 'bacon': 0.13636363636363635, 'dog': 0.13636363636363635, 'cat': 0.27272727272727271, 'green': 0.18181818181818182, 'bumpy': 0.090909090909090912, 'narwhal': 0.22727272727272727, 'happy': 0.22727272727272727}

In [5]:
# Let's define some helper functions

# calculates the PMI numerator
def PMInum (col1, col2, row_len):
    return sum(col1*col2/float(row_len))

# calculates the PMI denominator
def PMIdenom (col1, col2):
    return col1*col2

# calculates PMI quotient
def PMI (num, denom):
    return log(num/denom, 2)

In [12]:
# now to calculate PMI!!!
indexLen = len(dataNoUser.index) # number of rows
column_names= list(crossmat.columns.values) # list of the column names

# Loop through the columns
for i in range(0,len(crossmat.columns)):
    # Loop through the columns for each column
    for j in range(0,len(crossmat.columns)):
        numerator = PMInum(dataNoUser.ix[:,i], dataNoUser.ix[:,j], indexLen) #calculate numerator of PMI
        denominator = PMIdenom(sing_probs[column_names[i]], sing_probs[column_names[j]]) #calculate denom. of PMI
        if numerator/denominator == 0: #avoid log(0)
            crossmat.ix[i,j] = -1
        else:
            #calculate PMI total
            crossmat.ix[i,j] = PMI(numerator, denominator)/(-log(numerator,2))
            
crossmat

,cat,dog,economics,green,narwhal,happy,bacon,bumpy,crazy,holy,keys
cat,1,0.06492007,0.08368618,-0.02814953,-0.1003399,0.1597202,-1,0.5418431,0.3042193,0.01940035,-1
dog,0.06492007,1,0.06492007,0.1960943,0.1239039,-1,0.2891639,-1,0.06492007,0.01504994,-1
economics,0.08368618,0.06492007,1,-1,-0.1003399,0.3957265,0.372751,0.5418431,-1,-0.2091939,-1
green,-0.02814953,0.1960943,-1,1,0.03083432,-1,0.1960943,-1,-0.02814953,-0.07801965,-1
narwhal,-0.1003399,0.1239039,-0.1003399,0.03083432,1,-0.04135607,-1,-1,0.1597202,-0.15021,-1
happy,0.1597202,-1,0.3957265,-1,-0.04135607,1,-1,0.6178771,-0.1003399,-1,-1
bacon,-1,0.2891639,0.372751,0.1960943,-1,-1,1,-1,-1,0.01504994,-1
bumpy,0.5418431,-1,0.5418431,-1,-1,0.6178771,-1,1,-1,-1,-1
crazy,0.3042193,0.06492007,-1,-0.02814953,0.1597202,-0.1003399,-1,-1,1,0.4338865,0.1960943
holy,0.01940035,0.01504994,-0.2091939,-0.07801965,-0.15021,-1,0.01504994,-1,0.4338865,1,0.1462242
keys,-1,-1,-1,-1,-1,-1,-1,-1,0.1960943,0.1462242,1

In [8]:
# make a function to do all of this. This function could be cleaner as a series of modular parts.
def FileHeadings(filename):
    data = pd.read_csv(filename) #read in file
    data = data.drop('user',1) #drop the user column if necessary
    return data

def FileNoHeadings(filename):
    data = pd.read_csv(filename)
    return data

def MakePMI(filename):
    import pandas as pd
    from math import log
    data = FileHeadings(filename)
    # create data frame with column names on both axes
    crossmat = pd.DataFrame(index=data.columns, columns=data.columns)
    indexLen = len(dataNoUser.index) #number of rows

    sing_probs = dict() #establish empty dictionary for singular probabilities
    # fill dictionary 
    for x in dataNoUser:
        sing_probs[x] = sum(dataNoUser[x])/float(indexLen)
    
    # Let's define some helper functions

    # calculates the PMI numerator
    def PMInum (col1, col2, row_len):
        return sum(col1*col2/float(row_len))

    # calculates the PMI denominator
    def PMIdenom (col1, col2):
        return col1*col2

    # calculates PMI quotient
    def PMI (num, denom):
        return log(num/denom, 2)
    
    # now to calculate PMI!!!
    indexLen = len(dataNoUser.index) # number of rows
    column_names= list(crossmat.columns.values) # list of the column names

    # Loop through the columns
    for i in range(0,len(crossmat.columns)):
        # Loop through the columns for each column
        for j in range(0,len(crossmat.columns)):
            numerator = PMInum(dataNoUser.ix[:,i], dataNoUser.ix[:,j], indexLen) #calculate numerator of PMI
            denominator = PMIdenom(sing_probs[column_names[i]], sing_probs[column_names[j]]) #calculate denom. of PMI
            if numerator/denominator == 0: #avoid log(0)
                crossmat.ix[i,j] = 'UNDEF'
            else:
                #calculate PMI total
                crossmat.ix[i,j] = PMI(numerator, denominator)
    return crossmat

In [10]:
MakePMI('testwords.csv') # it works on my little test file

,cat,dog,economics,green,narwhal,happy,bacon,bumpy,crazy,holy,keys
cat,1.874469,0.2895066,0.2895066,-0.1255309,-0.447459,0.552541,UNDEF,1.874469,0.8744691,0.0671142,UNDEF
dog,0.2895066,2.874469,0.2895066,0.8744691,0.552541,UNDEF,1.289507,UNDEF,0.2895066,0.0671142,UNDEF
economics,0.2895066,0.2895066,1.874469,UNDEF,-0.447459,1.137504,1.289507,1.874469,UNDEF,-0.9328858,UNDEF
green,-0.1255309,0.8744691,UNDEF,2.459432,0.1375035,UNDEF,0.8744691,UNDEF,-0.1255309,-0.3479233,UNDEF
narwhal,-0.447459,0.552541,-0.447459,0.1375035,2.137504,-0.1844246,UNDEF,UNDEF,0.552541,-0.6698514,UNDEF
happy,0.552541,UNDEF,1.137504,UNDEF,-0.1844246,2.137504,UNDEF,2.137504,-0.447459,UNDEF,UNDEF
bacon,UNDEF,1.289507,1.289507,0.8744691,UNDEF,UNDEF,2.874469,UNDEF,UNDEF,0.0671142,UNDEF
bumpy,1.874469,UNDEF,1.874469,UNDEF,UNDEF,2.137504,UNDEF,3.459432,UNDEF,UNDEF,UNDEF
crazy,0.8744691,0.2895066,UNDEF,-0.1255309,0.552541,-0.447459,UNDEF,UNDEF,1.874469,1.067114,0.8744691
holy,0.0671142,0.0671142,-0.9328858,-0.3479233,-0.6698514,UNDEF,0.0671142,UNDEF,1.067114,1.652077,0.6520767
keys,UNDEF,UNDEF,UNDEF,UNDEF,UNDEF,UNDEF,UNDEF,UNDEF,0.8744691,0.6520767,3.459432

In [65]:
def turnToBinaryMatrix(M):
    nonZero = np.flatnonzero(M)
    np.put(M, nonZero, 1)
    return M

In [92]:
# make a function to do all of this. This function could be cleaner as a series of modular parts.
def FileNoHeadings(filename):
    data = pd.read_csv(filename, sep=' ')
    return data

def FlattenData(M):
    for i in range(0, len(M.index)):
        for j in range(0, len(M.columns)):
            if M.ix[i,j] != 0 and type(M.ix[i,j]) != str:
                M.ix[i,j] /= M.ix[i,j]
    return M

def turnToBinaryMatrix(M):
    import numpy as np
    nonZero = np.flatnonzero(M)
    np.put(M, nonZero, 1)
    return M

def MakePMInoHeadings(filename):
    import pandas as pd
    from math import log
    data = FileNoHeadings(filename)
    data = FlattenData(data)
    # create data frame with column names on both axes
    crossmat = pd.DataFrame(index=data.columns, columns=data.columns)
    indexLen = len(dataNoUser.index) #number of rows

    sing_probs = dict() #establish empty dictionary for singular probabilities
    # fill dictionary 
    for x in dataNoUser:
        sing_probs[x] = sum(dataNoUser[x])/float(indexLen)
    
    # Let's define some helper functions

    # calculates the PMI numerator
    def PMInum (col1, col2, row_len):
        return sum(col1*col2/float(row_len))

    # calculates the PMI denominator
    def PMIdenom (col1, col2):
        return col1*col2

    # calculates PMI quotient
    def PMI (num, denom):
        return log(num/denom, 2)
    
    # now to calculate PMI!!!
    indexLen = len(dataNoUser.index) # number of rows
    column_names= list(crossmat.columns.values) # list of the column names

    # Loop through the columns
    for i in range(0,len(crossmat.columns)):
        # Loop through the columns for each column
        for j in range(0,len(crossmat.columns)):
            numerator = PMInum(dataNoUser.ix[:,i], dataNoUser.ix[:,j], indexLen) #calculate numerator of PMI
            denominator = PMIdenom(sing_probs[column_names[i]], sing_probs[column_names[j]]) #calculate denom. of PMI
            if numerator/denominator == 0: #avoid log(0)
                crossmat.ix[i,j] = 'UNDEF'
            else:
                #calculate PMI total
                crossmat.ix[i,j] = PMI(numerator, denominator)
    return crossmat

In [93]:
MakePMInoHeadings('userGroupMatrix_top50Groups.txt')

KeyError: '0'